services:
    photobooth_app:
        build: .
        container_name: photobooth_app
        ports:
            - "8015:8000"
        environment:
            - TZ=Asia/Jakarta
        volumes:
            # current working directory = data folder
            - ./photobooth-data:/data
            - /mnt/pb_share/tmp:/tmp
            - /mnt/pb_share/media:/opt/photobooth-app/media
        restart: unless-stopped

        # DIBUTUHKAN hanya jika pakai DSLR via gphoto2
        # privileged: true
        # devices:
        #  - /dev/bus/usb:/dev/bus/usb
